[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:redis]
command=redis-server --save "" --appendonly no --bind 0.0.0.0
priority=1
autorestart=true

[program:uvicorn]
command=uv run uvicorn src.main:app --host 0.0.0.0 --port 8001
directory=/app
priority=2
autorestart=true

[program:chainlit]
command=uv run chainlit run frontend/app.py --host 0.0.0.0 --port 8000
directory=/app
priority=3
autorestart=true
